version: '3.8'
services:
  cache:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass huRnD@csMipzvD8
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - cache:/data
  shortening-service:
    image: shortening-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIRECT_DOMAIN=http://localhost:3000
      - PORT=3000
      - COUNTER_WORKERS=8
      - REDIS_HOSTNAME=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=huRnD@csMipzvD8
    ports:
      - ${PORT}:${PORT}
    volumes:
      - store:/database/sqlite
volumes:
  cache:
  store:
